"""
Project Euler #2
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

def sum_of_even_numbers_of_fibonacci_suite_under_limit(limit: int):
    """
    Give the sum of all even values of the fibonacci inferior or egal to the the limit

    Args:
        limit (int): Limit of the fibonacci suite

    Returns:
        int: Return a sum
    """

    numbers_sum = 0

    if isinstance(limit, int):
        first_value = 0
        second_value = 1

        while True:
            third_value = first_value + second_value

            if third_value > limit:
                break

            first_value = second_value
            second_value = third_value

            if second_value % 2 == 0:
                numbers_sum += second_value

    return numbers_sum

def get_int_value_from_prompt(msg: str):
    """
    Get an integer value from user input

    Args:
        msg (str): The prompt message to display

    Returns:
        int: The user input
    """

    while True:
        try:
            return int(input(msg).strip())
        except ValueError:
            print("Please enter an integer!")


if __name__ == '__main__':
    print("*" * 7 + "Welcome to Euler Project #2" + "*" * 7)

    limit_input = get_int_value_from_prompt("Enter the limit: ")
    numbers_sum_output = sum_of_even_numbers_of_fibonacci_suite_under_limit(limit_input)

    print("The sum of even values of the fibonacci suite under " +
        f"{limit_input} is {numbers_sum_output}.")
